### ISSUE TITLE
環境構築時にgitbook init で、「TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Promise」発生

### ISSUE THREAD

**Issue by gurezo** [mozilla-japan/translation-work-procedure#1]
gitbook init で、下記エラー発生

```
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Promise
```

gitbook-cli で、issue が立っている
- https://github.com/GitbookIO/gitbook-cli/issues/110
- https://github.com/GitbookIO/gitbook-cli/issues/115

**Comment by yoshinorin** [comment]
@gurezo 

gitbookの代わりに [honkit](https://github.com/honkit/honkit) を使用するのはどうでしょうか？

gitbookはOSS版はもう [メンテしないと宣言してあります](https://github.com/GitbookIO/gitbook)。gitbook から Forkされたのが honkit で基本的に gitbook と互換があるという認識です。（すみません、両方とも実際に使用したことはないのですが...）

**Comment by gurezo** [comment]
@yoshinorin 
情報ありがとうございます！
試してフィードバックしますね！

**Comment by gurezo** [comment]
hokit で、開発すすめるので close
